services:
  db:
    image: mysql:8.0
    container_name: mysql_employees
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: employees
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d